### PR TITLE
Disable auto setting latest docker tag. Fix paths for uploading swagg…

### PR DESCRIPTION
**Pull request by maciejmrowiec**
…er to S3.

Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
better to wait with this until I'll switch all tests on master tag from latest, I'll merge it later

**Comment by bboozzoo** [comment]
So we're not going to tag master images as latest?

**Comment by maciejmrowiec** [comment]
most common usage pattern for `latest` is to point it to newest stable releases, in our case that will be `1.0.0` this will be part of the release process

**Comment by maciejmrowiec** [comment]
changes to integration will follow this one

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano

**Pull request merged**
