### PR TITLE
auth acceptance tests 

### PR DESCRIPTION
**Pull request by bboozzoo**
@mendersoftware/rndity @maciejmrowiec

### CODE REVIEW

**Comment by bboozzoo** [comment]
the tests should be fixed and all passing now

**Comment by bboozzoo** [comment]
rebase on top of master

**Comment by bboozzoo** [comment]
the integration test was failing for unrelated reasons, pushed again to see if it'll fail again

**Comment by bboozzoo** [comment]
merge?

**Comment by bboozzoo** [comment]
do we need to backport this?

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano ^^

**Comment by GregorioDiStefano** [comment]
any good reason not to back-port this to 1.2.x?

1.1.x is lacking multi-tenancy, and 1.0.x is approaching EOL, so the only potential target I see here is 1.2.x

**Comment by bboozzoo** [comment]
None of the changes is a bugfix (well, maybe the docs update but it's fixing the internal API). The changes to tests depend on earlier changes that are only in the master branch. If we wanted to merge the fixes from this PR, we'd also have to pull in the rest. I would recommend not backporting this to 1.2.x.

**Comment by GregorioDiStefano** [comment]
Okay, that makes sense.

**Pull request merged**
