### PR TITLE
Immutable demo user

### PR DESCRIPTION
**Pull request by merlin-northern**
Prevent the deletion and updates of Demo user, which should be left unchanged at all times
as specified by https://tracker.mender.io/browse/MC-574

ChangeLog: title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by estenberg** [comment]
But should this be part of the product?
Won't this make this demo user hardcoded on all open source on-premise installations (even production ones), as well as Enterprise onprem ones? I don't think that's desirable; the demo user is only supposed to be an integration "extension" to HM?

**Comment by merlin-northern** [comment]
> But should this be part of the product?
> Won't this make this demo user hardcoded on all open source on-premise installations (even production ones), as well as Enterprise onprem ones? I don't think that's desirable; the demo user is only supposed to be an integration "extension" to HM?

good call! we had been discussing it, thats why it is not being merged until we think of something. the problem is that more and more things are diverging, this is one example, where only HM wants this feature. other are on-prem requests (one of which we discussed in Oslo last time), which will mean branching of integration repo. Enterprise is another example, where some differences are bound to appear. Currently we are not ready with our model to handle all this. I think we should talk about it.
 This can stay in code, and not be activated unless someone configures it (the default value needs to be changed and two ifs as well), in that way it will be present in code but will not work, unless someone explicitly reaches for it by providing demo user name in configuration of the services.

**Comment by estenberg** [comment]
OK. Configurable (default off) could work unless it introduces some attack vector and could be flagged by audits.

I think we need to aim for all editions of the product to remain on the same codebase (except closed features), otherwise it will be chaos and a lot of maintenance overhead. Configuration can be different, though.

**Comment by 0lmi** [comment]
Current version of demo environment is supposed to be not perfect and we all knew and accepted all imperfections of current solution before starting implementing it. Tries to improve something which is bad by design by making changes in codebase with all consequences is not the way as it should be.

**Pull request closed without merging**
