### PR TITLE
MEN-3153: add support for fallback RSA private key

### PR DESCRIPTION
**Pull request by tranchitella**
MEN-3153: add support for fallback RSA private key

New configuration setting (server_fallback_priv_key_path) and env
variable (USERADM_SERVER_FALLBACK_PRIV_KEY_PATH) to specify a
fallback RSA private key to be used to verify signatures on JWT token.

Specifying a fallback RSA private key it is possible to rotate the
private key used by the service.

Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Review by merlin-northern — COMMENTED** [review]
just for the record, what happens when we need to rotate the keys again?

**Comment by tranchitella** [comment]
@merlin-northern the JWT tokens expire in one week, thus you move the active key to fallback for one week, then you remove it.

**Comment by merlin-northern** [comment]
> @merlin-northern the JWT tokens expire in one week, thus you move the active key to fallback for one week, then you remove it.

right! so, since we have all the knowledge in here, we can maintain a list of fallback keys with TTL set accordingly.

**Comment by merlin-northern** [comment]
> > @merlin-northern the JWT tokens expire in one week, thus you move the active key to fallback for one week, then you remove it.
> 
> right! so, since we have all the knowledge in here, we can maintain a list of fallback keys with TTL set accordingly.

perhaps it is an overkill, so treat it as an idle comment:
* we introduce a command `./useradm rotate-key`
* the command inserts the current key into the `fallback_keys` collection in the db with TTL
* generates a new key
* we consult all the keys from the `fallback_keys` collection

**Comment by tranchitella** [comment]
> > > @merlin-northern the JWT tokens expire in one week, thus you move the active key to fallback for one week, then you remove it.
> > 
> > 
> > right! so, since we have all the knowledge in here, we can maintain a list of fallback keys with TTL set accordingly.
> 
> perhaps it is an overkill, so treat it as an idle comment:
> 
> * we introduce a command `./useradm rotate-key`
> * the command inserts the current key into the `fallback_keys` collection in the db with TTL
> * generates a new key
> * we consult all the keys from the `fallback_keys` collection

You don't want to store the private key in the database. It's a secret, we keep it in Kubernetes (as secret) and it never leaves the service's memory. The problem with the fallback keys is that we have to loop over them, and this is very expensive. I strongly believe one fallback key is enough, and this particular key rotation will require one week of "idle time", I will document it in `saas`.

**Comment by merlin-northern** [comment]
> > > > @merlin-northern the JWT tokens expire in one week, thus you move the active key to fallback for one week, then you remove it.
> > > 
> > > 
> > > right! so, since we have all the knowledge in here, we can maintain a list of fallback keys with TTL set accordingly.
> > 
> > 
> > perhaps it is an overkill, so treat it as an idle comment:
> > 
> > * we introduce a command `./useradm rotate-key`
> > * the command inserts the current key into the `fallback_keys` collection in the db with TTL
> > * generates a new key
> > * we consult all the keys from the `fallback_keys` collection
> 
> You don't want to store the private key in the database. It's a secret, we keep it in Kubernetes (as secret) and it never leaves the service's memory. The problem with the fallback keys is that we have to loop over them, and this is very expensive. I strongly believe one fallback key is enough, and this particular key rotation will require one week of "idle time", I will document it in `saas`.

I know -- but the fallback keys are not secret any more -- they are rotated because they were "compromised". and I agree about the looping over the keys. of course we can still do it all in redis we do not have to use mongo. ok, thanks for answering.

**Review by merlin-northern — APPROVED** [review]

**Comment by tranchitella** [comment]
@merlin-northern Redis is not an option, because it is not persistent (in our configuration), we use it as a cache. I believe this single fallback-based approach is enough to do yearly key rotation, with one week cooling time. @0lmi @mchalski what do you think? I'll wait your reviews before merging.

**Comment by 0lmi** [comment]
`but the fallback keys are not secret any more -- they are rotated because they were "compromised"`
not necessarily, for improving security keys might be rotated by a schedule

**Comment by tranchitella** [comment]
Ok, let's merge then.

**Pull request merged**
