### PR TITLE
MEN-2375 send unauthorized repsonse for logins with empty username

### PR DESCRIPTION
**Pull request by merlin-northern**
@kjaskiewiczz please take a look.

related ticket:
https://tracker.mender.io/browse/MEN-2375

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
you need to update copyright date

**Comment by merlin-northern** [comment]
> you need to update copyright date

done! thanks, forgot about that.

**Comment by merlin-northern** [comment]
> > you need to update copyright date
> 
> done! thanks, forgot about that.

@kjaskiewiczz sorry, I had to force push, due to the fact that tests were failingsince I forgot to signoff the commits. Squashed them also. Is it ok?

**Comment by merlin-northern** [comment]
sorry @kjaskiewiczz had to close this one, those tests will not pass, and I want to make it properly.

**Pull request closed without merging**
