### PR TITLE
travis: deploy useradm docs to site docs

### PR DESCRIPTION
**Pull request by mchalski**
supposedly, this magic will make useradm's swagger appear in the docs site.
goes with https://github.com/mendersoftware/mender-docs/pull/100
Issues: MEN-976

Signed-off-by: mchalczynski <marcin.chalczynski@rndity.com>

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano

**Comment by GregorioDiStefano** [comment]
looks good

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano should I force push ?

**Comment by GregorioDiStefano** [comment]
only one way to find out if it works

**Comment by maciejmrowiec** [comment]
here it goes ...
keep an eye ;)

**Pull request merged**
