### PR TITLE
fix: invalidate user sessions but the current one on user updates

### PR DESCRIPTION
**Pull request by 0lmi**
Changelog: Title
Ticket: MEN-5731
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>

### CODE REVIEW

**Comment by 0lmi** [comment]
@mender-test-bot start pipeline

**Comment by 0lmi** [comment]
@mender-test-bot start pipeline

**Comment by 0lmi** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]

**Comment by 0lmi** [comment]
@mender-test-bot start pipeline

**Pull request merged**
