### PR TITLE
multitenant migrations, server --automigrate command

### PR DESCRIPTION
**Pull request by mchalski**
Issues: https://tracker.mender.io/browse/MEN-1255

Requires https://github.com/mendersoftware/go-lib-micro/pull/29 (merged) and https://github.com/mendersoftware/integration/pull/342

@maciejmrowiec @mendersoftware/rndity 

EDIT: this needed a build with params for integration tests to pass - it finished successfully:
https://mender-jenkins.mender.io/job/mender-builder/2229/console

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
`12:42:01 store/mongo/datastore_mongo.go:318: unknown field 'Automigrate' in struct literal of type migrate.DummyMigrator`

**Comment by mchalski** [comment]
@GregorioDiStefano yes yes, this will fail until the referenced pr is merged

**Comment by GregorioDiStefano** [comment]
just pointing it out

**Comment by mchalski** [comment]
@mendersoftware/rndity ping

**Pull request merged**
